/**
 * Validering og normalisering av bygningsmodellen.
 *
 * Modellen lagres som JSONB, og kan komme fra tre kanter: editoren, KI-en og
 * gamle rader. Alt går derfor gjennom `parseBuildingModel`, som er tilgivende
 * (fyller inn defaults) men aldri slipper gjennom geometri som knekker
 * renderer eller mengdeuttrekk — degenererte vegger, åpninger utenfor veggen,
 * polygoner med for få punkter.
 */

import { z } from "zod"

import { dedupePolygon, roundMm } from "./math"
import { DEFAULTS, createDefaultMaterials, newId, storeyName } from "./presets"
import type { BuildingModel, Storey, Wall } from "./types"

const finite = (fallback: number) =>
  z
    .number()
    .refine((value) => Number.isFinite(value), { message: "Må være et tall" })
    .catch(fallback)

const pointSchema = z.object({
  x: finite(0),
  y: finite(0),
})

const openingSchema = z.object({
  id: z.string().min(1).catch(() => newId("op")),
  kind: z.enum(["door", "window", "opening"]).catch("window"),
  distance: finite(0),
  width: finite(1).pipe(z.number().min(0.05).max(50).catch(1)),
  height: finite(1).pipe(z.number().min(0.05).max(20).catch(1)),
  sill: finite(0),
  label: z.string().nullish().catch(null),
  materialId: z.string().nullish().catch(null),
})

const wallSchema = z.object({
  id: z.string().min(1).catch(() => newId("w")),
  a: pointSchema,
  b: pointSchema,
  thickness: finite(DEFAULTS.interiorWallThickness).pipe(
    z.number().min(0.01).max(3).catch(DEFAULTS.interiorWallThickness)
  ),
  height: finite(DEFAULTS.storeyHeight).pipe(
    z.number().min(0.1).max(30).catch(DEFAULTS.storeyHeight)
  ),
  baseOffset: finite(0),
  type: z.enum(["exterior", "interior", "load_bearing", "partition"]).catch("interior"),
  openings: z.array(openingSchema).max(80).catch([]),
  materialId: z.string().nullish().catch(null),
  exteriorMaterialId: z.string().nullish().catch(null),
  interiorMaterialId: z.string().nullish().catch(null),
  locked: z.boolean().optional().catch(false),
  label: z.string().nullish().catch(null),
})

const slabSchema = z.object({
  id: z.string().min(1).catch(() => newId("sl")),
  kind: z.enum(["floor", "ceiling", "deck", "foundation"]).catch("floor"),
  outline: z.array(pointSchema).max(400).catch([]),
  thickness: finite(DEFAULTS.slabThickness).pipe(
    z.number().min(0.01).max(3).catch(DEFAULTS.slabThickness)
  ),
  offset: finite(0),
  materialId: z.string().nullish().catch(null),
  label: z.string().nullish().catch(null),
  locked: z.boolean().optional().catch(false),
})

const roofSchema = z.object({
  id: z.string().min(1).catch(() => newId("rf")),
  kind: z.enum(["flat", "mono", "gable"]).catch("gable"),
  outline: z.array(pointSchema).max(400).catch([]),
  baseHeight: finite(0),
  pitchDeg: finite(DEFAULTS.roofPitchDeg).pipe(
    z.number().min(0).max(75).catch(DEFAULTS.roofPitchDeg)
  ),
  directionDeg: finite(0),
  thickness: finite(DEFAULTS.roofThickness).pipe(
    z.number().min(0.02).max(2).catch(DEFAULTS.roofThickness)
  ),
  overhang: finite(DEFAULTS.roofOverhang).pipe(z.number().min(0).max(5).catch(DEFAULTS.roofOverhang)),
  materialId: z.string().nullish().catch(null),
  label: z.string().nullish().catch(null),
  locked: z.boolean().optional().catch(false),
})

const columnSchema = z.object({
  id: z.string().min(1).catch(() => newId("col")),
  position: pointSchema,
  width: finite(DEFAULTS.columnSize).pipe(z.number().min(0.02).max(5).catch(DEFAULTS.columnSize)),
  depth: finite(DEFAULTS.columnSize).pipe(z.number().min(0.02).max(5).catch(DEFAULTS.columnSize)),
  height: finite(DEFAULTS.storeyHeight).pipe(z.number().min(0.1).max(30).catch(DEFAULTS.storeyHeight)),
  baseOffset: finite(0),
  rotationDeg: finite(0),
  materialId: z.string().nullish().catch(null),
  label: z.string().nullish().catch(null),
  locked: z.boolean().optional().catch(false),
})

const spaceSchema = z.object({
  id: z.string().min(1).catch(() => newId("sp")),
  name: z.string().max(120).catch("Rom"),
  outline: z.array(pointSchema).max(400).catch([]),
  autoGenerated: z.boolean().catch(true),
  floorMaterialId: z.string().nullish().catch(null),
  wallMaterialId: z.string().nullish().catch(null),
  ceilingMaterialId: z.string().nullish().catch(null),
})

const storeySchema = z.object({
  id: z.string().min(1).catch(() => newId("st")),
  name: z.string().max(80).catch("Etasje"),
  elevation: finite(0),
  height: finite(DEFAULTS.storeyHeight).pipe(
    z.number().min(0.5).max(30).catch(DEFAULTS.storeyHeight)
  ),
  walls: z.array(wallSchema).max(2000).catch([]),
  slabs: z.array(slabSchema).max(400).catch([]),
  roofs: z.array(roofSchema).max(200).catch([]),
  columns: z.array(columnSchema).max(500).catch([]),
  spaces: z.array(spaceSchema).max(400).catch([]),
  visible: z.boolean().optional().catch(true),
})

const materialSchema = z.object({
  id: z.string().min(1).catch(() => newId("mat")),
  name: z.string().min(1).max(160).catch("Materiale"),
  category: z.enum(["wall", "floor", "roof", "opening", "structure", "other"]).catch("other"),
  color: z
    .string()
    .regex(/^#[0-9a-fA-F]{6}$/)
    .catch("#cccccc"),
  unit: z.string().max(16).catch("m2"),
  measure: z.enum(["area", "length", "volume", "count"]).catch("area"),
  factor: finite(1).pipe(z.number().min(0.0001).max(1000).catch(1)),
  wastePercent: finite(0).pipe(z.number().min(0).max(100).catch(0)),
  supplier: z.string().nullish().catch(null),
  nobb: z.string().nullish().catch(null),
  supplierSku: z.string().nullish().catch(null),
  unitPriceNok: z.number().nullish().catch(null),
  notes: z.string().nullish().catch(null),
})

const metaSchema = z.object({
  gridSize: finite(DEFAULTS.gridSize).pipe(z.number().min(0.01).max(10).catch(DEFAULTS.gridSize)),
  northAngleDeg: finite(0),
  notes: z.string().nullish().catch(null),
  source: z.enum(["manual", "ai", "import"]).catch("manual"),
  generatedAt: z.string().nullish().catch(null),
  generatedModel: z.string().nullish().catch(null),
  assumptions: z.array(z.string().max(400)).max(30).catch([]),
})

export const buildingModelSchema = z.object({
  schemaVersion: z.literal(1).catch(1),
  name: z.string().min(1).max(160).catch("3D-modell"),
  units: z.literal("m").catch("m"),
  storeys: z.array(storeySchema).max(30).catch([]),
  materials: z.array(materialSchema).max(400).catch([]),
  meta: metaSchema.catch({
    gridSize: DEFAULTS.gridSize,
    northAngleDeg: 0,
    notes: null,
    source: "manual",
    generatedAt: null,
    generatedModel: null,
    assumptions: [],
  }),
})

export function createEmptyStorey(index = 0, elevation = 0): Storey {
  return {
    id: newId("st"),
    name: storeyName(index),
    elevation,
    height: DEFAULTS.storeyHeight,
    walls: [],
    slabs: [],
    roofs: [],
    columns: [],
    spaces: [],
    visible: true,
  }
}

export function createEmptyModel(name = "3D-modell"): BuildingModel {
  return {
    schemaVersion: 1,
    name,
    units: "m",
    storeys: [createEmptyStorey(0, 0)],
    materials: createDefaultMaterials(),
    meta: {
      gridSize: DEFAULTS.gridSize,
      northAngleDeg: 0,
      notes: null,
      source: "manual",
      generatedAt: null,
      generatedModel: null,
      assumptions: [],
    },
  }
}

function normalizeWall(wall: Wall, storeyHeight: number): Wall | null {
  const a = { x: roundMm(wall.a.x), y: roundMm(wall.a.y) }
  const b = { x: roundMm(wall.b.x), y: roundMm(wall.b.y) }
  const wallLength = Math.hypot(b.x - a.x, b.y - a.y)

  // Nullvegger ville gitt NaN-normaler nedstrøms (retning = 0/0).
  if (wallLength < 0.02) return null

  const height = wall.height > 0 ? roundMm(wall.height) : storeyHeight
  const thickness = roundMm(wall.thickness)

  const seenOpeningIds = new Set<string>()
  const openings = wall.openings
    .map((opening) => {
      const width = Math.min(roundMm(opening.width), wallLength)
      const height2 = Math.min(roundMm(opening.height), height)
      // Hold åpningen innenfor veggen — ellers får vi negative delstykker.
      const halfWidth = width / 2
      const distance = Math.min(Math.max(roundMm(opening.distance), halfWidth), wallLength - halfWidth)
      const sill = Math.min(Math.max(roundMm(opening.sill), 0), Math.max(height - height2, 0))
      const id = seenOpeningIds.has(opening.id) ? newId("op") : opening.id
      seenOpeningIds.add(id)
      return { ...opening, id, width, height: height2, distance, sill }
    })
    .filter((opening) => opening.width > 0.02 && opening.height > 0.02)
    .sort((left, right) => left.distance - right.distance)

  return {
    ...wall,
    a,
    b,
    thickness,
    height,
    baseOffset: roundMm(wall.baseOffset),
    openings,
  }
}

/**
 * Rydder modellen etter parsing: avrunder til millimeter, kaster degenerert
 * geometri og sikrer unike id-er. Kalles både ved lasting og før lagring, slik
 * at databasen aldri får inn en modell editoren ikke kan tegne.
 */
export function sanitizeModel(model: BuildingModel): BuildingModel {
  const seenIds = new Set<string>()
  const uniqueId = (id: string, prefix: string) => {
    if (!seenIds.has(id)) {
      seenIds.add(id)
      return id
    }
    const replacement = newId(prefix)
    seenIds.add(replacement)
    return replacement
  }

  const storeys = model.storeys.map((storey, index) => {
    const height = storey.height > 0 ? roundMm(storey.height) : DEFAULTS.storeyHeight

    const walls = storey.walls
      .map((wall) => normalizeWall(wall, height))
      .filter((wall): wall is Wall => wall !== null)
      .map((wall) => ({ ...wall, id: uniqueId(wall.id, "w") }))

    const slabs = storey.slabs
      .map((slab) => ({
        ...slab,
        id: uniqueId(slab.id, "sl"),
        outline: dedupePolygon(
          slab.outline.map((point) => ({ x: roundMm(point.x), y: roundMm(point.y) }))
        ),
        thickness: roundMm(slab.thickness),
        offset: roundMm(slab.offset),
      }))
      .filter((slab) => slab.outline.length >= 3)

    const roofs = storey.roofs
      .map((roof) => ({
        ...roof,
        id: uniqueId(roof.id, "rf"),
        outline: dedupePolygon(
          roof.outline.map((point) => ({ x: roundMm(point.x), y: roundMm(point.y) }))
        ),
        baseHeight: roundMm(roof.baseHeight),
        thickness: roundMm(roof.thickness),
        overhang: roundMm(roof.overhang),
      }))
      .filter((roof) => roof.outline.length >= 3)

    const columns = storey.columns.map((column) => ({
      ...column,
      id: uniqueId(column.id, "col"),
      position: { x: roundMm(column.position.x), y: roundMm(column.position.y) },
      width: roundMm(column.width),
      depth: roundMm(column.depth),
      height: roundMm(column.height),
      baseOffset: roundMm(column.baseOffset),
    }))

    const spaces = storey.spaces
      .map((space) => ({
        ...space,
        id: uniqueId(space.id, "sp"),
        outline: dedupePolygon(
          space.outline.map((point) => ({ x: roundMm(point.x), y: roundMm(point.y) }))
        ),
      }))
      .filter((space) => space.outline.length >= 3)

    return {
      ...storey,
      id: uniqueId(storey.id, "st"),
      name: storey.name || storeyName(index),
      elevation: roundMm(storey.elevation),
      height,
      walls,
      slabs,
      roofs,
      columns,
      spaces,
    }
  })

  const materialIds = new Set<string>()
  const materials = model.materials.map((material) => {
    const id = materialIds.has(material.id) ? newId("mat") : material.id
    materialIds.add(id)
    return { ...material, id }
  })

  return {
    ...model,
    storeys: storeys.length > 0 ? storeys : [createEmptyStorey(0, 0)],
    materials,
  }
}

/**
 * Leser en modell fra ukjent JSON. Kaster aldri — en ødelagt rad skal gi en tom
 * modell brukeren kan jobbe videre i, ikke en hvit skjerm.
 */
export function parseBuildingModel(raw: unknown, fallbackName = "3D-modell"): BuildingModel {
  if (!raw || typeof raw !== "object" || Object.keys(raw as object).length === 0) {
    return createEmptyModel(fallbackName)
  }

  const result = buildingModelSchema.safeParse(raw)
  if (!result.success) {
    return createEmptyModel(fallbackName)
  }

  const parsed = result.data as BuildingModel
  if (parsed.storeys.length === 0) {
    parsed.storeys = [createEmptyStorey(0, 0)]
  }
  if (parsed.materials.length === 0) {
    parsed.materials = createDefaultMaterials()
  }

  return sanitizeModel(parsed)
}
