/**
 * Datamodell for ProAnbud CAD.
 *
 * Modellen er PARAMETRISK, ikke en trekantsuppe: en vegg er en senterlinje med
 * tykkelse og høyde, et vindu er en posisjon langs veggen. Det er dette som gjør
 * at brukeren kan dra i hva som helst i ettertid, at mengdeuttrekket blir
 * eksakt (ikke estimert fra mesh), og at IFC-eksporten blir ekte BIM-objekter
 * i stedet for døde flater.
 *
 * Enheter: METER overalt, avrundet til millimeter (se roundMm i math.ts).
 * Vinkler: grader.
 * Plan-koordinater: x mot øst, y mot nord. Høyde (z) ligger i `elevation`/
 * `height`-feltene — planet er alltid 2D, høyden er alltid parametrisk.
 */

export type Point = { x: number; y: number }

export type WallType = "exterior" | "interior" | "load_bearing" | "partition"

export type OpeningKind = "door" | "window" | "opening"

export type SlabKind = "floor" | "ceiling" | "deck" | "foundation"

export type RoofKind = "flat" | "mono" | "gable"

export type MaterialCategory =
  | "wall"
  | "floor"
  | "roof"
  | "opening"
  | "structure"
  | "other"

/**
 * En tilordnbar byggevare/arbeidsressurs. Brukeren velger denne på en flate i
 * 3D-visningen, og mengdeuttrekket ganger opp areal/lengde/volum mot den.
 * Kan peke på en rad i bedriftens prisfil, eller stå frittstående.
 */
export type CadMaterial = {
  id: string
  name: string
  category: MaterialCategory
  /** Hex-farge brukt i 3D-visningen. */
  color: string
  /** Enheten mengden regnes ut i: m2 | m | m3 | stk. */
  unit: string
  /** Hvordan mengden utledes fra geometrien. */
  measure: "area" | "length" | "volume" | "count"
  /** Antall enheter per målte enhet (f.eks. 0.5 plater per m²). Default 1. */
  factor: number
  /** Svinn i prosent som legges på i mengdeuttrekket. */
  wastePercent: number
  supplier?: string | null
  nobb?: string | null
  supplierSku?: string | null
  unitPriceNok?: number | null
  notes?: string | null
}

export type Opening = {
  id: string
  kind: OpeningKind
  /** Avstand i meter fra veggens startpunkt (a) til åpningens SENTER. */
  distance: number
  width: number
  height: number
  /** Underkant åpning, meter over veggens bunn. Dør = 0. */
  sill: number
  label?: string | null
  materialId?: string | null
}

export type Wall = {
  id: string
  a: Point
  b: Point
  thickness: number
  height: number
  /** Bunn av vegg, meter over etasjens gulvnivå. */
  baseOffset: number
  type: WallType
  openings: Opening[]
  /** Hovedmateriale (kledning/overflate) brukt i 3D og mengdeuttrekk. */
  materialId?: string | null
  /** Egne materialer per side, når ut- og innside er forskjellige. */
  exteriorMaterialId?: string | null
  interiorMaterialId?: string | null
  locked?: boolean
  label?: string | null
}

export type Slab = {
  id: string
  kind: SlabKind
  outline: Point[]
  thickness: number
  /** Overkant dekke, meter relativt til etasjens gulvnivå. */
  offset: number
  materialId?: string | null
  label?: string | null
  locked?: boolean
}

export type Roof = {
  id: string
  kind: RoofKind
  outline: Point[]
  /** Underkant tak (raft), meter over etasjens gulvnivå. */
  baseHeight: number
  /** Takvinkel i grader. Ignoreres for flatt tak. */
  pitchDeg: number
  /** Mønets/fallets retning i grader (0 = mot øst). */
  directionDeg: number
  thickness: number
  /** Utstikk i meter utenfor omrisset. */
  overhang: number
  materialId?: string | null
  label?: string | null
  locked?: boolean
}

export type Column = {
  id: string
  position: Point
  width: number
  depth: number
  height: number
  baseOffset: number
  rotationDeg: number
  materialId?: string | null
  label?: string | null
  locked?: boolean
}

/**
 * Rom. Omrisset genereres automatisk fra veggene (se rooms.ts), men kan
 * overstyres manuelt — derfor `autoGenerated`.
 */
export type Space = {
  id: string
  name: string
  outline: Point[]
  autoGenerated: boolean
  /** Gulvbelegg/overflate tilordnet rommet. */
  floorMaterialId?: string | null
  wallMaterialId?: string | null
  ceilingMaterialId?: string | null
}

export type Storey = {
  id: string
  name: string
  /** Gulvnivå i meter over terreng/referansenivå. */
  elevation: number
  /** Standard veggehøyde i etasjen. */
  height: number
  walls: Wall[]
  slabs: Slab[]
  roofs: Roof[]
  columns: Column[]
  spaces: Space[]
  visible?: boolean
}

export type BuildingModelMeta = {
  /** Rutenett i meter (snapping). */
  gridSize: number
  /** Byggets rotasjon mot nord, i grader. */
  northAngleDeg: number
  notes?: string | null
  source?: "manual" | "ai" | "import"
  generatedAt?: string | null
  generatedModel?: string | null
  /** KI-ens egne forbehold — vises som banner over editoren. */
  assumptions?: string[]
}

export type BuildingModel = {
  schemaVersion: 1
  name: string
  units: "m"
  storeys: Storey[]
  materials: CadMaterial[]
  meta: BuildingModelMeta
}

// ---------------------------------------------------------------------------
// Avledet geometri (beregnet, aldri lagret)
// ---------------------------------------------------------------------------

/** Veggens fotavtrykk i planet, med gjæret hjørne mot nabovegger. */
export type WallFootprint = {
  wallId: string
  /** Venstre side sett fra a mot b. */
  left: [Point, Point]
  /** Høyre side sett fra a mot b. */
  right: [Point, Point]
  /** Senterlinjens parameterområde etter gjæring (kan gå utenfor [0, lengde]). */
  uStart: number
  uEnd: number
  length: number
  direction: Point
  normal: Point
}

/** Et rektangulært delstykke av en vegg (mellom/over/under åpninger). */
export type WallPart = {
  /** Parameter langs fotavtrykket, 0–1. */
  t0: number
  t1: number
  /** Høyde relativt veggens bunn. */
  y0: number
  y1: number
  role: "full" | "under" | "over" | "between"
}

export type SolidMesh = {
  positions: number[]
  indices: number[]
}

export type ElementKind =
  | "wall"
  | "opening"
  | "slab"
  | "roof"
  | "column"
  | "space"

/** Et byggbart volum klart for tegning, IFC-eksport og visuell utvelgelse. */
export type ElementSolid = {
  id: string
  elementId: string
  elementKind: ElementKind
  storeyId: string
  materialId: string | null
  mesh: SolidMesh
  /**
   * Satt når volumet er en ren vertikal ekstrudering av et plan-polygon.
   * IFC-eksporten bruker dette til å skrive ekte IfcExtrudedAreaSolid i stedet
   * for en faceted brep.
   */
  extrusion?: {
    profile: Point[]
    /** Bunn og topp i meter over referansenivå (etasje medregnet). */
    z0: number
    z1: number
  }
}

export type SelectionRef =
  | { kind: "wall"; id: string; storeyId: string }
  | { kind: "opening"; id: string; wallId: string; storeyId: string }
  | { kind: "slab"; id: string; storeyId: string }
  | { kind: "roof"; id: string; storeyId: string }
  | { kind: "column"; id: string; storeyId: string }
  | { kind: "space"; id: string; storeyId: string }
